/**
 * BSD 3-Clause License
 *
 * Copyright (c) 2026, RavenHammer Research Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// Shared long-option name -> DNS record type mapping for PowerDNSManager.
// Included from PowerDNSManager.cpp.

#ifndef POWERDNS_RECORD_OPTION
#define POWERDNS_RECORD_OPTION(name, type)
#endif

POWERDNS_RECORD_OPTION("a", "A")
POWERDNS_RECORD_OPTION("aaaa", "AAAA")
POWERDNS_RECORD_OPTION("mx", "MX")
POWERDNS_RECORD_OPTION("ns", "NS")
POWERDNS_RECORD_OPTION("cname", "CNAME")
POWERDNS_RECORD_OPTION("soa", "SOA")
POWERDNS_RECORD_OPTION("txt", "TXT")
POWERDNS_RECORD_OPTION("ptr", "PTR")
POWERDNS_RECORD_OPTION("srv", "SRV")
POWERDNS_RECORD_OPTION("caa", "CAA")
POWERDNS_RECORD_OPTION("hinfo", "HINFO")
POWERDNS_RECORD_OPTION("minfo", "MINFO")
POWERDNS_RECORD_OPTION("rp", "RP")
POWERDNS_RECORD_OPTION("afsdb", "AFSDB")
POWERDNS_RECORD_OPTION("sig", "SIG")
POWERDNS_RECORD_OPTION("key", "KEY")
POWERDNS_RECORD_OPTION("gpos", "GPOS")
POWERDNS_RECORD_OPTION("loc", "LOC")
POWERDNS_RECORD_OPTION("nxt", "NXT")
POWERDNS_RECORD_OPTION("naptr", "NAPTR")
POWERDNS_RECORD_OPTION("kx", "KX")
POWERDNS_RECORD_OPTION("cert", "CERT")
POWERDNS_RECORD_OPTION("ds", "DS")
POWERDNS_RECORD_OPTION("sshfp", "SSHFP")
POWERDNS_RECORD_OPTION("tlsa", "TLSA")
POWERDNS_RECORD_OPTION("spf", "SPF")
POWERDNS_RECORD_OPTION("uri", "URI")
POWERDNS_RECORD_OPTION("alias", "ALIAS")
POWERDNS_RECORD_OPTION("wks", "WKS")
POWERDNS_RECORD_OPTION("a6", "A6")
POWERDNS_RECORD_OPTION("dname", "DNAME")
POWERDNS_RECORD_OPTION("apl", "APL")
POWERDNS_RECORD_OPTION("rrsig", "RRSIG")
POWERDNS_RECORD_OPTION("nsec", "NSEC")
POWERDNS_RECORD_OPTION("dnskey", "DNSKEY")
POWERDNS_RECORD_OPTION("dhcid", "DHCID")
POWERDNS_RECORD_OPTION("nsec3", "NSEC3")
POWERDNS_RECORD_OPTION("nsec3param", "NSEC3PARAM")
POWERDNS_RECORD_OPTION("cds", "CDS")
POWERDNS_RECORD_OPTION("cdnskey", "CDNSKEY")
POWERDNS_RECORD_OPTION("openpgpkey", "OPENPGPKEY")
POWERDNS_RECORD_OPTION("svcb", "SVCB")
POWERDNS_RECORD_OPTION("https", "HTTPS")
POWERDNS_RECORD_OPTION("eui48", "EUI48")
POWERDNS_RECORD_OPTION("eui64", "EUI64")
POWERDNS_RECORD_OPTION("tkey", "TKEY")
POWERDNS_RECORD_OPTION("dlv", "DLV")

#undef POWERDNS_RECORD_OPTION
